#!/usr/bin/env python3
"""
ניקוי Hard Links קיימים — סקריפט חד-פעמי.
מוחק קבצים כפולים ומייצר _IMG_ALIAS.js עם מפת הפניות.

שימוש:
    python cleanup_hardlinks.py                # הרצה
    python cleanup_hardlinks.py --dry-run      # תצוגה מקדימה בלבד
"""
import hashlib, os, sys, time
from pathlib import Path
from collections import defaultdict

DRY_RUN = '--dry-run' in sys.argv

IMG_DIR = Path(__file__).parent / "images"
ALIAS_FILE = Path(__file__).parent / "_IMG_ALIAS.js"

def log(msg):
    ts = time.strftime('%H:%M:%S')
    print(f"[{ts}] {msg}", flush=True)

def main():
    log("=" * 60)
    log("Cleanup Hard Links" + (" [DRY RUN]" if DRY_RUN else ""))
    log("=" * 60)

    if not IMG_DIR.exists():
        log(f"ERROR: {IMG_DIR} not found"); return

    # ── Scan all images by SHA256 ──
    log("Scanning images (SHA256)...")
    by_hash = defaultdict(list)
    count = 0
    for p in sorted(IMG_DIR.glob("r-*.jpg")):
        try:
            data = p.read_bytes()
            if len(data) > 0:
                h = hashlib.sha256(data).hexdigest()
                by_hash[h].append(p)
                count += 1
        except OSError:
            pass

    dup_groups = {h: ps for h, ps in by_hash.items() if len(ps) > 1}
    total_dups = sum(len(ps) - 1 for ps in dup_groups.values())
    total_bytes = sum(ps[0].stat().st_size * (len(ps) - 1) for ps in dup_groups.values())

    log(f"Files scanned : {count}")
    log(f"Unique images : {len(by_hash)}")
    log(f"Dup groups    : {len(dup_groups)}")
    log(f"Files to delete: {total_dups}")
    log(f"Space to free : {total_bytes / 1024 / 1024:.1f} MB")
    log("")

    if total_dups == 0:
        log("No duplicates found.")
        return

    # ── Delete duplicates, build alias map ──
    alias_map = {}
    ok = 0
    freed = 0

    for h, paths in sorted(dup_groups.items(), key=lambda x: -(len(x[1]) - 1)):
        canon = paths[0]
        sz = canon.stat().st_size
        canon_name = canon.stem

        for dup in paths[1:]:
            dup_name = dup.stem
            if DRY_RUN:
                log(f"  DRY  {dup.name:30s} -> {canon.name}  ({sz//1024} KB)")
            else:
                try:
                    dup.unlink()
                except OSError as e:
                    log(f"  FAIL {dup.name}: {e}")
                    continue
            alias_map[dup_name] = canon_name
            ok += 1
            freed += sz

    # ── Write _IMG_ALIAS.js ──
    lines = [
        "/* Auto-generated by cleanup_hardlinks.py */",
        f"/* {len(alias_map)} aliases, {freed / 1024 / 1024:.1f} MB freed */",
        "var _IMG_ALIAS = {",
    ]
    for k in sorted(alias_map.keys()):
        lines.append(f"  '{k}':'{alias_map[k]}',")
    lines.append("};")

    ALIAS_FILE.write_text("\n".join(lines), encoding="utf-8")

    log("")
    log("=" * 60)
    if DRY_RUN:
        log(f"DRY RUN: {ok} duplicates found, {freed / 1024 / 1024:.1f} MB to free")
    else:
        log(f"Deleted: {ok} files | Freed: {freed / 1024 / 1024:.1f} MB")
    log(f"Alias map: {ALIAS_FILE} ({len(alias_map)} entries)")
    log(f"Copy _IMG_ALIAS.js content into index.html")
    log("=" * 60)

if __name__ == "__main__":
    main()
