/* Auto-generated by download_images.py — do NOT edit manually */
/* Maps deleted duplicate images to their canonical file */
/* 14 aliases, 6.8 MB freed */
var _IMG_ALIAS = {
  'r-c2-2':'r-c1',
  'r-c4':'r-c1',
  'r-f2-2':'r-f1',
  'r-h1':'r-c2',
  'r-h3':'r-c2',
  'r-m2':'r-m1',
  'r-s5':'r-s2',
  'r-s7':'r-s2',
  'r-s8':'r-s1',
  'r-sa2':'r-s2',
  'r-sa4':'r-c2',
  'r-sa7':'r-s2',
  'r-v1':'r-s2',
  'r-v3':'r-s6',
};